---
- hosts: 10.0.1.69
  become: yes
  name: Install PowerShell on web1
  tasks:
    - name: Install the Microsoft RedHat repository GPG keys
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
    - name: Download the Microsoft RedHat repository package
      get_url:
        url: https://packages.microsoft.com/config/rhel/9/prod.repo
        dest: /etc/yum.repos.d/microsoft-prod.repo
    - name: Install the Microsoft RedHat repository package
      dnf:
        name: /etc/yum.repos.d/microsoft-prod.repo
        state: present
    - name: Update package index files
      dnf:
        update_cache: yes
    - name: Install PowerShell
      dnf:
        name: powershell
        state: present
    - name: Remove the Microsoft RedHat repository package file
      file:
        path: /etc/yum.repos.d/microsoft-prod.repo
        state: absent